name: openradar-3d
channels:
  - defaults
dependencies:
  - python=3.10.9
  - setuptools=75.8.0
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.15.2
  - matplotlib=3.10.0
  - pyserial=3.5
  - scikit-learn=1.6.1
  - pip=25.0